### ISSUE TITLE
Data portability link doesn't expire in two weeks

### ISSUE THREAD

**Issue by luigigubello** [pagopa/io-infrastructure-modules-new#220]
I'm not sure if this is the right repo to report this issue. The data portability link (`iopstuserdatadownload.blob.windows.net`), that users receive in the IO App messages if they require their data, doesn't expire in two weeks, as written in the message.

**Comment by pasqualedevita** [comment]
@luigigubello thank you we fixed this issue in https://github.com/pagopa/io-infrastructure-live-new/pull/637
